target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'models', :path => '../models'
  pod 'integrations', :path => '../integrations'
  pod 'database', :path => '../database'
  pod 'shared', :path => '../shared'
end