target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'models', :path => '../models'
  pod 'integrations', :path => '../integrations'
  pod 'database', :path => '../database'
  pod 'shared', :path => '../shared'

  pre_install do |installer|
    FileUtils.mkdir_p(installer.sandbox.root.to_s + '/../../shared/build/generated/libres/apple/libres-bundles')
  end
end